-- DEPRECADO: no ejecutar en arranque.
-- El esquema se aplica de forma incremental desde backend/db/migrations/
-- mediante backend/src/db/migrate.ts (tabla schema_migrations).
--
-- Para resetear por completo la base en desarrollo:
--   docker compose -f docker-compose.dev.yml down -v
--   docker compose -f docker-compose.dev.yml up --build
