ALTER TABLE concurso_obras
  ADD COLUMN IF NOT EXISTS book_slug VARCHAR(64),
  ADD COLUMN IF NOT EXISTS autor VARCHAR(255),
  ADD COLUMN IF NOT EXISTS rol VARCHAR(255),
  ADD COLUMN IF NOT EXISTS edad VARCHAR(8),
  ADD COLUMN IF NOT EXISTS challenge_intro TEXT,
  ADD COLUMN IF NOT EXISTS challenge_headline TEXT,
  ADD COLUMN IF NOT EXISTS descripcion_reto TEXT,
  ADD COLUMN IF NOT EXISTS entregable TEXT,
  ADD COLUMN IF NOT EXISTS formatos JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS requisitos JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS nota_participacion TEXT;

-- Contenido inicial LQL2026 (desde books.ts del sitio público)
UPDATE concurso_obras o SET
  book_slug = v.slug,
  autor = v.autor,
  rol = v.rol,
  edad = v.edad,
  challenge_intro = v.challenge_intro,
  challenge_headline = v.challenge_headline,
  descripcion_reto = v.descripcion_reto,
  entregable = v.entregable,
  formatos = v.formatos::jsonb,
  requisitos = v.requisitos::jsonb,
  nota_participacion = v.nota
FROM concursos c,
LATERAL (VALUES
  (
    'Tusuj, un cuy especial',
    'tusuj-6',
    'Andrea Paz / Claudia Paz',
    'Soy un(a) compositor(a).',
    '+6',
    NULL,
    'Escribe una rima basada en el cuento y la ilustra.',
    'Escribe una rima basada en «Tusuj, un cuy especial», con cuatro versos, e ilústrala.',
    'Archivo PDF. Hoja formato A4. Orientación horizontal. Extensión de cuatro (4) versos, con ilustración hecha a mano.',
    '["PDF"]',
    '["Solo una participación por estudiante","El PDF debe ser legible y en orientación horizontal (A4)","Cuatro versos con ilustración hecha a mano","Incluye tu nombre, grado y colegio en el archivo o en el formulario de envío","Tu colegio debe estar inscrito en Loqueleo"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'La lonchera mentirosa',
    'lonchera-6',
    'Jorge Eslava',
    'Soy un(a) amigo(a).',
    '+6',
    'En el libro hay personajes con personalidades muy distintas. Piensa en cuál te habría gustado conocer de verdad.',
    NULL,
    'Escribe una carta de una página como si le hablaras a ese personaje: preséntate, cuéntale algo de ti y dile por qué quieres ser su amigo o su amiga.',
    NULL,
    '["PDF","Foto legible de hoja escrita a mano"]',
    '["Una carta por participante","Letra clara; si escribes a mano, escanea con buena luz","No más de dos carillas","Firma con tu nombre completo al final","Participa desde un colegio registrado en el concurso"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'Libros revueltos',
    'revueltos-8',
    'Lorenzo Helguero',
    'Soy un(a) lector(a).',
    '+8',
    'La familia del libro vive entre libros y pantallas. Seguro tú también tienes una escena favorita.',
    NULL,
    'Graba un audio o un video de máximo 3 minutos recomendándole el libro a un compañero que no lo ha leído. Cuéntale qué pasa, sin spoilear el final, y por qué vale la pena.',
    NULL,
    '["Audio MP3","Video hasta 3 min"]',
    '["Una recomendación por estudiante","Menciona al menos un momento que te haya gustado","Habla claro y sin música muy fuerte de fondo","Identifícate con nombre y colegio al empezar","Colegio inscrito en Soy Loqueleo 2026"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'Tres gallinas contra un pícaro ladrón',
    'gallinas-8',
    'Vicky Canales',
    'Soy un(a) reportero(a).',
    '+8',
    'Las tres gallinas armaron un plan para atrapar al ladrón. Tú puedes contar otra versión de lo que pasó en el granero.',
    NULL,
    'Redacta una noticia con titular, entradilla y cuerpo: ¿qué robó el pícaro?, ¿cómo reaccionaron las gallinas?, ¿hubo final feliz? Inventa detalles, pero que suene a crónica de verdad.',
    NULL,
    '["PDF","Documento de texto"]',
    '["Una noticia por participante","Titular llamativo y texto ordenado en párrafos","Extensión máxima: dos páginas","Al pie, tu nombre y sección o grado","Desde colegio registrado en Loqueleo"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'El corazón de Misha',
    'corazon-misha-10',
    'Jorge Eslava',
    'Soy un(a) propagandista.',
    '+10',
    'Misha vive una historia intensa en la selva. Piensa qué imagen o frase haría que alguien quiera abrir el libro hoy mismo.',
    NULL,
    'Diseña un afiche digital (como los que ves en el pasillo del colegio) que anuncie el libro. Incluye título, una frase breve y algún elemento visual que represente la historia.',
    NULL,
    '["PDF","JPG o PNG en buena resolución"]',
    '["Un afiche por estudiante","Tamaño mínimo equivalente a una hoja A4","Que se lea el nombre del libro sin forzar la vista","Tu nombre en una esquina","Colegio participante del concurso"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'Comando Espacial 2',
    'comando-espacial-10',
    'Iván Bolaños Gamero',
    'Soy un(a) inventor(a).',
    '+10',
    'El Comando Espacial usa artefactos muy particulares. ¿Y si tu equipo necesitara un invento nuevo para la siguiente misión?',
    NULL,
    'Crea un invento original (dibujo, maqueta en foto o infografía) y explícalo en video de hasta 3 minutos o en un PDF con imágenes: nombre del invento, para qué sirve y cómo se usa.',
    NULL,
    '["Video hasta 3 min","PDF con esquemas o fotos"]',
    '["Un invento por participante","Debe relacionarse con la aventura espacial del libro","Explica con tus palabras, no copies texto del libro","Indica tu nombre y grado en el archivo","Colegio registrado en Loqueleo"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'Yute & Tocuyo, El Salto a las Nubes',
    'yute-tocuyo-12',
    'Rafael Lanfranco',
    'Soy un(a) escritor(a).',
    '+12',
    'Yute y Tocuyo se atreven a algo imposible. Tu reto es seguir esa energía y abrir un capítulo nuevo.',
    NULL,
    'Escribe el comienzo de una aventura (entre una y tres páginas) donde los personajes intenten dar un salto a las nubes. Puedes usar a Yute y Tocuyo u otros nombres, pero mantén el espíritu del libro.',
    NULL,
    '["PDF"]',
    '["Un relato por estudiante","Entre 1 y 3 páginas, letra tamaño 12","Primera página con título, tu nombre y colegio","Cuídate de copiar párrafos del libro original","Participación válida solo con colegio inscrito"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'La maleta de la libertad',
    'maleta-libertad-12',
    'Iván Thays',
    'Soy un(a) fabulador(a).',
    '+12',
    'En la novela, la maleta guarda más que ropa. Si tú armaras la tuya para un viaje importante, ¿qué llevarías?',
    NULL,
    'Cuenta en un relato breve o en un video de hasta 3 minutos qué objetos meterías en tu maleta de la libertad y qué significa cada uno. Puedes ser simbólico: no hace falta que sean cosas reales.',
    NULL,
    '["PDF","Video hasta 3 min"]',
    '["Un trabajo por estudiante","Relaciona tus objetos con la idea de libertad del libro","Video: cámara fija y buen audio","Texto: máximo tres páginas","Colegio inscrito en el concurso"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'Ocho segundos',
    'ocho-14',
    'María Fernanda Heredia',
    'Soy un(a) booktoker.',
    '+14',
    'Ocho segundos habla de decisiones que cambian todo en muy poco tiempo. Es un libro ideal para contarlo en voz alta y directo.',
    NULL,
    'Graba un video vertical, estilo recomendación rápida, de máximo 60 segundos. Di de qué trata, qué te enganchó y a quién le regalarías el libro, sin contar el final.',
    NULL,
    '["MP4 vertical","Máximo 60 segundos"]',
    '["Un video por participante","Duración real: hasta 1 minuto","Menciona título y autora al inicio","Evita canciones con copyright; mejor voz sola o sonido ambiente suave","Colegio registrado en Loqueleo"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'La tía Levita',
    'levita-14',
    'Javier Arévalo',
    'Soy un(a) periodista.',
    '+14',
    'La tía Levita guarda secretos que el pueblo comenta a media voz. Un buen periodista sabe hacer las preguntas difíciles.',
    NULL,
    'Escribe una entrevista ficticia a Levita o a otro personaje del libro. Mínimo ocho preguntas con respuestas que revelen algo nuevo sobre la historia, en tono de revista o programa de radio.',
    NULL,
    '["PDF"]',
    '["Una entrevista por estudiante","Formato claro: pregunta y respuesta","Hasta cuatro páginas en total","Tu nombre al final del documento","Desde institución educativa registrada"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  ),
  (
    'Sol tan lejos',
    'sol-14',
    'Jorge Eslava',
    'Soy un(a) crítico(a).',
    '+14',
    'Sol tan lejos mezcla memoria, viaje y fotografía. Como crítico literario, tu lectura puede ayudar a otro estudiante a decidir si es su próximo libro.',
    NULL,
    'Escribe una reseña de al menos 200 palabras: de qué va, qué funcionó para ti, qué te dejó con dudas y qué tipo de lector lo disfrutaría más.',
    NULL,
    '["PDF","Texto en procesador"]',
    '["Una reseña por participante","Mínimo 200 palabras, sin contar título ni datos","Opinión propia; no resúmenes copiados de internet","Incluye tu nombre y colegio","Colegio participante del concurso"]',
    'Al participar te pediremos ubicación, colegio, datos de tu docente, DNI, datos de tu apoderado y el archivo de tu trabajo. El formulario te tomará unos minutos; te recomendamos tener todo a mano.'
  )
) AS v(nombre, slug, autor, rol, edad, challenge_intro, challenge_headline, descripcion_reto, entregable, formatos, requisitos, nota)
WHERE o.concurso_id = c.id
  AND c.codigo = 'LQL2026'
  AND o.nombre_obra = v.nombre;
